FROM python:3.13-slim
# If using debian-based (python:3.13-slim)
RUN apt-get update && apt-get install -y curl && rm -rf /var/lib/apt/lists/*

# OR If using alpine-based (python:3.13-alpine)
# RUN apk add --no-network curl

# create a workdir
WORKDIR /code

# copy the requirements to workdir and install deps
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# add a user other than admin, prevent from running as root
RUN useradd -m sam
USER sam

# copy app code AFTER installing the deps
COPY ./app /code/app

CMD ["fastapi", "run", "app/main.py", "--port", "8800"]
